"""CV-tailoring — step 2 of the two-step flow (see docs/cv-tailoring.md).

Fills the fixed, checked-in docxtpl template (`templates/cv_template.docx`) from a
validated `TailoredCV` and writes the result to a random `/tmp` file. The template
is regenerated by `templates/build_cv_template.py`, whose placeholders bind 1:1 to
`TailoredCV` field names.

SSTI is not a risk here: the template is authored by us and fixed, and only
validated field *values* are ever substituted as `{{ field }}` placeholders — never
compiled as template source. Two invariants keep that true and must not be broken:
never route a Claude/visitor-influenced field through docxtpl's RichText / raw-XML /
subdoc pass-through, and never feed rendered output back into a second `render()`.
"""

from __future__ import annotations

import secrets
from pathlib import Path

import jinja2
from docxtpl import DocxTemplate

from app.cv_tailor import TailoredCV

TEMPLATE_PATH = Path(__file__).parent / "templates" / "cv_template.docx"

# Nothing is ever written outside /tmp (repo rule). The filename stem is a
# 256-bit capability token — later reused as the in-memory store key and the
# download URL's path segment.
OUTPUT_DIR = Path("/tmp")


def render_cv(cv: TailoredCV) -> str:
    """Render `cv` to a `.docx` in /tmp and return its absolute path.

    The file is named `<secrets.token_urlsafe(32)>.docx`; the stem is the download
    token. Raises `jinja2.UndefinedError` if the template references a field the
    contract no longer has — surfacing placeholder/field drift loudly at render
    time rather than emitting a silently-blank CV.
    """
    out_path = OUTPUT_DIR / f"{secrets.token_urlsafe(32)}.docx"

    doc = DocxTemplate(str(TEMPLATE_PATH))
    # StrictUndefined: fail loudly on drift. autoescape: XML-escape substituted
    # values so real content ('… Manager & Architect') can't corrupt the docx.
    jinja_env = jinja2.Environment(undefined=jinja2.StrictUndefined, autoescape=True)
    doc.render(cv.model_dump(), jinja_env=jinja_env)
    doc.save(str(out_path))

    return str(out_path)
